### ISSUE TITLE
java.lang.Error: randomChoiceUnnormalized falls through -- negative components in input distribution?

### ISSUE THREAD

**Issue by bjoelle** [tgvaughan/BDMM-Prime#4]
error above appears halfway through the run
attached XML and screen output, let me know if I'm doing something wrong
[issue_files.zip](https://github.com/tgvaughan/BDMM-Prime/files/5961651/issue_files.zip)

**Comment by tgvaughan** [comment]
Sorry for the huge delay!  This just means that numerical errors are creeping into the stochastic mapping.  This should have improved since you posted the issue.
